### ISSUE TITLE
Error in comment?

### ISSUE THREAD

**Issue by drewnoakes** [spencerchubb/solver#3]
https://github.com/spencerchubb/solver/blob/cddf1f70f6ffe9751b3265b621076dd1d46daf7c/solver/src/cube.rs#L7

Should be:

```diff
-00 09 02 02 11 03 03 10 02 02 08 00
+00 09 02 02 11 03 03 10 01 01 08 00
```

**Comment by spencerchubb** [comment]
I believe you're correct. Thank you, and I'll make the change!
